using PhysioAssist.Api.Shared.Dtos.Pdf;
using QuestPDF.Fluent;
using QuestPDF.Helpers;

namespace PhysioAssist.Api.Shared.PdfService;

public class PdfService(IMediaStorageService mediaStorageService, ILogger<PdfService> logger) : IPdfService
{
    public async Task<Result<string>> GeneratePdfAsync(
        PdfDocumentContent content, string folder, string publicId, CancellationToken ct = default)
    {
        byte[] pdfBytes;
        try
        {
            pdfBytes = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header().Text(content.Title)
                        .SemiBold().FontSize(20).FontColor(Colors.Teal.Darken2);

                    page.Content().PaddingVertical(20).Column(column =>
                    {
                        column.Spacing(10);
                        foreach (var section in content.Sections)
                        {
                            if (section.Heading is not null)
                                column.Item().PaddingTop(15).Text(section.Heading).SemiBold();

                            foreach (var paragraph in section.Paragraphs)
                                column.Item().Text(paragraph);

                            if (section.ImageBytes is not null)
                                column.Item().PaddingTop(10).AlignCenter().Height(140).Image(section.ImageBytes);
                        }
                    });

                    page.Footer().AlignCenter()
                        .Text(content.FooterText ?? "Generated by PhysioAssist")
                        .FontSize(9).FontColor(Colors.Grey.Medium);
                });
            }).GeneratePdf();
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "PDF generation failed for {PublicId}", publicId);
            return Result.Failure<string>(PdfErrors.GenerationFailed);
        }

        try
        {
            using var stream = new MemoryStream(pdfBytes);
            var fileUrl = await mediaStorageService.UploadRawFileAsync(stream, folder, publicId, "pdf");
            return Result.Success(fileUrl);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "PDF upload failed for {PublicId}", publicId);
            return Result.Failure<string>(PdfErrors.UploadFailed);
        }
    }
}
