using PhysioAssist.Api.Shared.Dtos.Pdf;
using PhysioAssist.Api.Shared.Interfaces;
using PhysioAssist.Api.Shared.Interfaces.Common;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace PhysioAssist.Api.Shared.PdfService;

public class PdfService(IMediaStorageService mediaStorageService) : IPdfService
{
    private readonly IMediaStorageService _mediaStorageService = mediaStorageService;

    public async Task<string> GenerateTreatmentPlanPdfAsync(TreatmentPlanPdfRequest request)
    {
        var pdfBytes = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header()
                    .Text("PhysioAssist — Treatment Plan")
                    .SemiBold().FontSize(20).FontColor(Colors.Teal.Darken2);

                page.Content()
                    .PaddingVertical(20)
                    .Column(column =>
                    {
                        column.Spacing(10);

                        column.Item().Text($"Patient: {request.PatientFullName}");
                        column.Item().Text($"Doctor: {request.DoctorFullName}");
                        column.Item().Text($"Date: {request.ReportDate:yyyy-MM-dd}");

                        column.Item().PaddingTop(15).Text("Report").SemiBold();
                        column.Item().Text(request.ReportText);
                    });

                page.Footer()
                    .AlignCenter()
                    .Text("Generated by PhysioAssist")
                    .FontSize(9).FontColor(Colors.Grey.Medium);
            });
        }).GeneratePdf();

        using var stream = new MemoryStream(pdfBytes);
        var publicId = $"treatment-plan-{request.ReportId}";
        var folder = $"treatment-plans/{request.ReportId}";

        return await _mediaStorageService.UploadRawFileAsync(stream, folder, publicId, "pdf");
    }
}
